maven-build:
          script:
                      - mvn clean install -Dmaven.test.skip=true
          artifacts:
                paths:
                      - api/target/image-processing-api-*.jar
